<?php

namespace BlogBundle\Entity;

/**
 * OauthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OauthRepository extends \Doctrine\ORM\EntityRepository
{
}
