<?php

namespace BlogBundle\Entity;


/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
	public function searchPostByTitle($keyword)
	{
		$qb = $this->createQueryBuilder('p');
		$query = $qb->where(' p.title like :filter')
			->andwhere('p.id > 0')
			->setParameter('filter', '%'.$keyword."%")
			->getQuery();
		return $query->getResult();
	}


}
