<?php

namespace BlogBundle\Entity;

use Symfony\Component\Security\Core\User\UserInterface;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
  public function loadUserByUsername($username)
  {
    return $this->createQueryBuilder('u')
      ->where('u.account = :username OR u.email = :email')
      ->setParameter('username', $username)
      ->setParameter('email', $username)
      ->getQuery()
      ->getOneOrNullResult();
  }



}
