# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        BlogBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        blog_user:
            entity: { class: BlogBundle\Entity\User }
        in_memory:
            memory: ~

    role_hierarchy:
        ROLE_USER: ['ROLE_VISTOR']
        ROLE_ADMIN: ['ROLE_ALLOWED_TO_SWITCH']


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - blog.security.from.login
            provider: blog_user

            logout:
                path: blog_security_logout
                target: blog_security_login

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        #- { path: ^/post, role: ROLE_USER }
